### ISSUE TITLE
404 when connect to http web

### ISSUE THREAD

**Issue by Trongbach** [andrew-ld/smart-tv-telegram#10]
Can I use http web to view stream video? When I conenct to 127.0.0.1:8330 (ip and port set in config.ini) it respone 404, I can not get video to play on web.

**Comment by andrew-ld** [comment]
hello, there is no web interface, everything is controlled from the bot telegram and from there you can select the various devices, if you really want a web interface you are free to do it

**Comment by Trongbach** [comment]
Can you give me some guideline to make a stream web? I can build flask web but don't know how to merge with your code.

**Comment by andrew-ld** [comment]
https://github.com/andrew-ld/smart-tv-telegram/commit/f3f57bb72136534f7fb8c348bf376f26e0c6d86e

**Comment by andrew-ld** [comment]
https://github.com/andrew-ld/smart-tv-telegram/commit/c39c96361a196445431a7753df68459ae1048df0

now it will be possible to make a web interface

**Comment by andrew-ld** [comment]
now you can play videos in the browser, the web interface is available at /static/index.html, you must set the password to config.ini and activate it, if you forward a video on telegram to the bot you can choose to play it in the browser

https://github.com/andrew-ld/smart-tv-telegram/commit/f41dc2b93140e03d96f53e2c22deca8f6d0a5274
