### ISSUE TITLE
noob questions

### ISSUE THREAD

**Issue by ayhoomsa** [andrew-ld/smart-tv-telegram#11]
Hello andrew, 
at first I am sry my bad english but i have many questions to ask :D  how should i install the  requirments for python? exam.:aiohttp and this stuff.. and after finishing the installation should i start any server? file? and how? and i have something called blocksize on bot option on config.ini what should i fill here? and my last question is: the listenhost and -port on http option.. should i write the ip adress from my phone or the device which i want play on?
 and merry Christmas :)

**Comment by andrew-ld** [comment]
to install the bot you have to execute only and exclusively these commands, you don't have to install any dependency manually:

```
git clone https://github.com/andrew-ld/smart-tv-telegram
cd smart-tv-telegram
python3 -m pip install wheel
python3 setup.py sdist bdist_wheel
python3 -m pip install dist/*.whl
```

the block_size can't be arbitrary, telegram only accepts certain sizes, I suggest you leave 1048576.

on listen_ip you must enter the local ip of the device acting as server, on listen_port any free port greater than 1024 (you can also use a lower port if you are root)

the bot is started by running the command "smart_tv_telegram", the command must be run in the same folder as the configuration file, by default the name of the file must be "config.ini".

**Comment by ayhoomsa** [comment]
another question about telegram bot.. should i paste only the token? and how can i connect them togeather? and can you please write the full command for running the server? and i will be very thankful

**Comment by andrew-ld** [comment]
the command is "smart_tv_telegram"
