### ISSUE TITLE
Docker automatic builds with GitHub Actions

### ISSUE THREAD

**Issue by MarcoBuster** [andrew-ld/smart-tv-telegram#13]
Hi, it would be cool to use GitHub Actions to build the Docker image then push it to the GitHub Container Registry or Docker Hub. 
If you want I can do it then send you a PR.

**Comment by andrew-ld** [comment]
already the docker is built automatically for x86_64, if you want to make a us for other architectures you are free to contribute

**Comment by MarcoBuster** [comment]
I think I will because I use ARM.
