### ISSUE TITLE
TV Addon

### ISSUE THREAD

**Issue by QNET17** [andrew-ld/smart-tv-telegram#17]
I am impressed and thank you for your work.

Would it be possible that you could provide a TV addon for Kodi.tv?

Best regards

**Comment by andrew-ld** [comment]
hi, currently i already support kodi using 2 different protocols, the first protocol is via upnp using avtransport, if you don't want to use upnp you can use it via its proprietary rpc 

support directly as a kodi addon is not expected.


take note that the telegram bot has no idea how devices work, the implementation of a device that actually controls kodi is not difficult

https://github.com/andrew-ld/smart-tv-telegram/tree/master/smart_tv_telegram/devices

**Comment by QNET17** [comment]
Thank you for the feedback.

Unfortunately, I lack the experience.

Can you possibly explain how to set up and use this with Kodi?
