### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by jake12334** [andrew-ld/smart-tv-telegram#19]
where should i put this: smart_tv_telegram -c config.ini -v 1 in the config file?
can you please explain?

**Comment by andrew-ld** [comment]
is a shell command

**Comment by jake12334** [comment]
> is a shell command

i tried running it in powershell but it won't work, it said that "smart_tv_telegram" is not an executable which is right because it is a folder...?

**Comment by andrew-ld** [comment]
you have to install it first, read the readme
