### ISSUE TITLE
Please help with installation

### ISSUE THREAD

**Issue by vijaykirann** [andrew-ld/smart-tv-telegram#20]
I have a RPI and a android tv . can you please help me set this up

**Comment by andrew-ld** [comment]
install kodi on android tv and activate upnp (including remote control) from settings (https://kodi.wiki/view/Settings/Services/UPnP_DLNA)

then install the bot on the rpi following the official guide (https://github.com/andrew-ld/smart-tv-telegram/blob/master/README.md)

now if you send a media to the bot via telegram you can choose to play it on the android tv (you must have kodi open)
