### ISSUE TITLE
Does not see "Chromecast with Google TV" device

### ISSUE THREAD

**Issue by johnd0e** [andrew-ld/smart-tv-telegram#30]
"Supported devices not found in the network"

**Comment by johnd0e** [comment]
BTW, I have tried https://github.com/home-assistant-libs/pychromecast and it can see ok.
```
D:\repo\pychromecast\examples (master)>discovery_example.py
Found cast device 'Bedroom speaker' with UUID 7cf2371c-c9f1-709f-f187-43bd44485a18
Currently known cast devices:
  'Bedroom speaker' (Google Nest Mini) @ 192.168.0.243:8009 uuid: 7cf2371c-c9f1-709f-f187-43bd44485a18
Found cast device 'TV' with UUID 36adeed0-21ba-5681-751d-c20a2b9ef119
Currently known cast devices:
  'Bedroom speaker' (Google Nest Mini) @ 192.168.0.243:8009 uuid: 7cf2371c-c9f1-709f-f187-43bd44485a18
  'TV' (Chromecast) @ 192.168.0.124:8009 uuid: 36adeed0-21ba-5681-751d-c20a2b9ef119
```

**Comment by andrew-ld** [comment]
there may be some things that don't allow the program to find chromecasts.

I remind you that in the config example chromecast_enabled by default is 0, you have to put it to 1 if you want to support chromecasts in the bot

if you are on docker try using --network=host

if it doesn't apply or doesn't work try increasing the scan timeout on config.ini

as a last attempt you can try updating the version of pychromecast used by this program, currently i don't have a chromecast where to try, if you can try the latest version of pychromecast probably it will be able to find the devices

**Comment by johnd0e** [comment]
Thank you!
The problem was that there is `chromecast_enabled=0` by default.
