### ISSUE TITLE
Feature request: The Telegram bot can accept a Youtube URL and stream the youtube video to devices

### ISSUE THREAD

**Issue by zhongkechen** [andrew-ld/smart-tv-telegram#34]
The admin user can send a Youtube URL to the Telegram bot. The bot will stream the Youtube video to the specified device.

**Comment by andrew-ld** [comment]
the linked youtube videos are not downloaded from the telegram servers, but a webview with the youtube iframe is started inside the client

**Comment by andrew-ld** [comment]
I am not going to add support for file sources other than telegram itself to limit the project maintenance activity
