### ISSUE TITLE
Running this on Rasberry pie

### ISSUE THREAD

**Issue by rajindersingh041** [andrew-ld/smart-tv-telegram#46]
Hi,

I gone through the read me and setup the config file.

[mtproto]
api_id=127xxx11x
api_hash=953acxxxxxxxxxx190fa7
token=751xxxxx01:AAxxxFQWfhxxxjCP2EB8CciDL4
session_name=smart_tv_telegram
file_fake_fw_wait=0.2

[bot]
admins=[595xxxxxxx2]
block_size=1048576
request_gone_timeout=900

[http]
listen_host=192.168.xxx.xxx
listen_port=xxx

[web_ui]
enabled=1
password=xxxxx

[discovery]
upnp_enabled=1
upnp_scan_timeout=3
chromecast_enabled=1
chromecast_scan_timeout=6
xbmc_enabled=0
xbmc_devices=[{"host": "192.168.42.140", "port": 8080},]
vlc_enabled=0
vlc_devices=[{"host": "127.0.0.1", "port": 4212, "password": "123"},]
device_request_timeout=10

I am running it throught the docker and container is healthy and running fine

![image](https://github.com/user-attachments/assets/fe45aaf0-7078-445c-ab86-d34507969093)

Container logs are also fine

![image](https://github.com/user-attachments/assets/0d13b583-f667-4a67-9afe-086cf8326a68)

I have enabled the webui and logged in with the password also. But the challenge is when I forward/upload any video file to bot, i don't see any option to forward this video to any player and i don't even see any logs in container

**Comment by andrew-ld** [comment]
this program require --network=host because send broadcasts to lan and is not possible with virtual network card

**Comment by rajindersingh041** [comment]
yes Rasberry pie is hosted on the network and all other devices like Chromecast, webbrowser etc are also hosted on same network. Pie is just being used to run the python script.

**Comment by andrew-ld** [comment]
--network=host on docker container !!!!!
